[package]
name = "sre"
version = "0.1.0"
authors = ["myl7 <myl@myl.moe>"]
edition = "2021"
description = "Symmetric revocable encryption implementation"
documentation = "https://github.com/myl7/sre#readme"
homepage = "https://github.com/myl7/sre"
repository = "https://github.com/myl7/sre.git"
license = "Apache-2.0"
keywords = ["crypto", "sre", "spe", "sse"]
categories = ["cryptography"]

[dependencies]
